namespace keyboard_capture_v2
{
	/// <summary>
	/// Static class with key variants for En and Ru languages, in both upper- and lowercase variants.
	/// </summary>
	public static class KeyOriginVariants
	{
		public static Dictionary<int, char> valueKeys()
		{
			return new Dictionary<int, char>()
			{
				{ 81, 'q' },
				{ 87, 'w' },
				{ 69, 'e' },
				{ 82, 'r' },
				{ 84, 't' },
				{ 89, 'y' },
				{ 85, 'u' },
				{ 73, 'i' },
				{ 79, 'o' },
				{ 80, 'p' },
				{ 219, '[' },
				{ 221, ']' },
				{ 65, 'a' },
				{ 83, 's' },
				{ 68, 'd' },
				{ 70, 'f' },
				{ 71, 'g' },
				{ 72, 'h' },
				{ 74, 'j' },
				{ 75, 'k' },
				{ 76, 'l' },
				{ 186, ';' },
				{ 222, '\'' },
				{ 220, '\\' },
				{ 90, 'z' },
				{ 88, 'x' },
				{ 67, 'c' },
				{ 86, 'v' },
				{ 66, 'b' },
				{ 78, 'n' },
				{ 77, 'm' },
				{ 188, ',' },
				{ 190, '.' },
				{ 191, '/' },
				{ 192, '`' },
				{ 49, '1' },
				{ 50, '2' },
				{ 51, '3' },
				{ 52, '4' },
				{ 53, '5' },
				{ 54, '6' },
				{ 55, '7' },
				{ 56, '8' },
				{ 57, '9' },
				{ 48, '0' },
				{ 189, '-' },
				{ 187, '=' },

			};
		}
		public static Dictionary<char, int> keyValues()
		{
			return valueKeys().ToDictionary(zxc => zxc.Value, zxc => zxc.Key);
		}
		public static List<char> origins()
		{
			return new List<char>()
			{
				'q',
				'w',
				'e',
				'r',
				't',
				'y',
				'u',
				'i',
				'o',
				'p',
				'[',
				']',
				'a',
				's',
				'd',
				'f',
				'g',
				'h',
				'j',
				'k',
				'l',
				';',
				'\'',
				'\\',
				'z',
				'x',
				'c',
				'v',
				'b',
				'n',
				'm',
				',',
				'.',
				'/',
				'`',
				'1',
				'2',
				'3',
				'4',
				'5',
				'6',
				'7',
				'8',
				'9',
				'0',
				'-',
				'=',
			};
		}
		public static List<List<char>> variants()
		{
			return new List<List<char>>()
			{
				"qQйЙ".ToList(),
				"wWцЦ".ToList(),
				"eEуУ".ToList(),
				"rRкК".ToList(),
				"tTеЕ".ToList(),
				"yYнН".ToList(),
				"uUгГ".ToList(),
				"iIшШ".ToList(),
				"oOщЩ".ToList(),
				"pPзЗ".ToList(),
				"[{хХ".ToList(),
				"]}ъЪ".ToList(),
				"aAфФ".ToList(),
				"sSыЫ".ToList(),
				"dDвВ".ToList(),
				"fFаА".ToList(),
				"gGпП".ToList(),
				"hHрР".ToList(),
				"jJоО".ToList(),
				"kKлЛ".ToList(),
				"lLдД".ToList(),
				";:жЖ".ToList(),
				"'\"эЭ".ToList(),
				"\\|\\/".ToList(),
				"zZяЯ".ToList(),
				"xXчЧ".ToList(),
				"cCсС".ToList(),
				"vVмМ".ToList(),
				"bBиИ".ToList(),
				"nNтТ".ToList(),
				"mMьЬ".ToList(),
				",<бБ".ToList(),
				".>юЮ".ToList(),
				"/?.,".ToList(),
				"`~ёЁ".ToList(),
				"1!1!".ToList(),
				"2@2\"".ToList(),
				"3#3№".ToList(),
				"4$4;".ToList(),
				"5%5%".ToList(),
				"6^6:".ToList(),
				"7&7?".ToList(),
				"8*8*".ToList(),
				"9(9(".ToList(),
				"0)0)".ToList(),
				"-_-_".ToList(),
				"=+=+".ToList(),
			};
		}
	}
}
